/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Decimal = string;
export interface InstantiateMsg {
  config: Config;
}
export interface Config {
  max_share_delta: Decimal;
  update_wait_period: number;
}
export type ExecuteMsg = {
  initialize_collection_residual: {
    collection: string;
  };
} | {
  set_collection_residual_default: {
    collection: string;
    recipient: string;
    share: Decimal;
  };
} | {
  update_collection_residual_default: {
    collection: string;
    decrement?: boolean | null;
    recipient?: string | null;
    share_delta?: Decimal | null;
  };
} | {
  set_collection_residual_protocol: {
    collection: string;
    protocol: string;
    recipient: string;
    share: Decimal;
  };
} | {
  update_collection_residual_protocol: {
    collection: string;
    decrement?: boolean | null;
    protocol: string;
    recipient?: string | null;
    share_delta?: Decimal | null;
  };
};
export type QueryMsg = {
  config: {};
} | {
  collection_residual_default: {
    collection: string;
  };
} | {
  collection_residual_protocol: {
    collection: string;
    protocol: string;
  };
} | {
  residual_protocol_by_collection: {
    collection: string;
    query_options?: QueryOptionsForString | null;
  };
} | {
  residual_payment: {
    collection: string;
    protocol?: string | null;
  };
};
export type QueryBoundForString = {
  inclusive: string;
} | {
  exclusive: string;
};
export interface QueryOptionsForString {
  descending?: boolean | null;
  limit?: number | null;
  max?: QueryBoundForString | null;
  min?: QueryBoundForString | null;
}
export type NullableResidualDefault = ResidualDefault | null;
export type Addr = string;
export type Timestamp = Uint64;
export type Uint64 = string;
export interface ResidualDefault {
  collection: Addr;
  residual_entry: ResidualEntry;
}
export interface ResidualEntry {
  recipient: Addr;
  share: Decimal;
  updated?: Timestamp | null;
}
export type NullableResidualProtocol = ResidualProtocol | null;
export interface ResidualProtocol {
  collection: Addr;
  protocol: Addr;
  residual_entry: ResidualEntry;
}
export interface ResidualPaymentResponse {
  residual_default?: ResidualDefault | null;
  residual_protocol?: ResidualProtocol | null;
}
export type ArrayOfResidualProtocol = ResidualProtocol[];